#!/usr/bin/env python3
"""Embed the single-file web UI; rerun after changing web/index.html."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
html = (root / 'web/index.html').read_text()
assert ')HOLIDAY"' not in html
(root / 'XIAO_ESP32_holiday_lights/web_app.h').write_text(
    '// Generated by tools/embed_web.py from web/index.html.\n#pragma once\n'
    'static const char holidayWebApp[] PROGMEM = R"HOLIDAY(' + html + ')HOLIDAY";\n')
